# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
#title: "The 14th ETSF Young Researchers' Meeting"
title: "ETSF YRM 2017"
email: etsf.yrm2017@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The 14th ETSF Young Researchers' Meeting,
  taking place June 5-9 2017 in Tarragona, Spain.
baseurl: ""
url: "https://yrm2017.github.io" # the base hostname & protocol for your site
twitter_username: yrm2017 
#github_username:  yrm2017
facebook_username: yrm2017

# Build settings
markdown: kramdown # redcarpet not supported by github.io
highlighter: rouge # rygments not supported by github.io
gems:
  - jemoji
  - jekyll-paginate


#blog logo
logo: '/assets/images/logo.png'
# blog cover
cover: "/assets/images/Logo-yrm-etsf3.png"
#cover: "/assets/images/blackboard.jpg"
name: 'YRM 2017'
author: 'YRM 2017'
author_image: "/assets/images/Logo-yrm-etsf3.png"
#author_image: "/assets/images/logo.png"
paginate:   3


# Site settings
#email:  yrm-info@kcl.ac.uk
#used to display twitter cards
# twitter_handle: '@dirkfabisch'
#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#social:
# - icon: facebook
#   url: https://www.facebook.com/yrm2017
#   desc: Find us on facebook
#   share_url: https://www.facebook.com/sharer.php
#   share_title: ?t=
#   share_link: "&amp;u="
